/**
 * @file ViewMachineStartTime.h
 * @author Lance Y.
 *
 *
 */

#ifndef CANADIANEXPERIENCE_CANADIANEXPERIENCELIB_VIEWMACHINESTARTTIME_H
#define CANADIANEXPERIENCE_CANADIANEXPERIENCELIB_VIEWMACHINESTARTTIME_H

class ViewMachineStartTime
{
private:

public:

};

#endif //CANADIANEXPERIENCE_CANADIANEXPERIENCELIB_VIEWMACHINESTARTTIME_H
